# Generated by Django 5.2.4 on 2026-04-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_providermonthlycost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providermonthlycost',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
