# Generated by Django 5.2.4 on 2026-07-20 17:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_remove_gemini_provider_cost_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('auto_recharge_enabled', models.BooleanField(default=True)),
                ('recharge_amount_eur', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('threshold_eur', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('last_recharge_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='billing.billingaccount')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('usage_debit', 'Usage debit'), ('auto_recharge', 'Auto recharge'), ('manual_recharge', 'Manual recharge'), ('admin_adjustment', 'Admin adjustment'), ('payment_failed', 'Payment failed')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('void', 'Void')], db_index=True, default='completed', max_length=32)),
                ('amount_eur', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after_eur', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wallet_transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.wallet')),
            ],
            options={
                'verbose_name': 'Wallet transaction',
                'verbose_name_plural': 'Wallet transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_type', 'status'], name='billing_wal_transac_4e53e7_idx'), models.Index(fields=['created_at'], name='billing_wal_created_b24001_idx')],
            },
        ),
    ]
