# Generated by Django 5.2.4 on 2026-04-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documentindex',
            new_name='integration_client__4b6cfb_idx',
            old_name='integratio_client__c0a241_idx',
        ),
        migrations.RenameIndex(
            model_name='documentindex',
            new_name='integration_client__c6f039_idx',
            old_name='integratio_client__5d6c56_idx',
        ),
        migrations.RenameIndex(
            model_name='documentindex',
            new_name='integration_client__81c9ee_idx',
            old_name='integratio_client__355574_idx',
        ),
        migrations.RenameIndex(
            model_name='documentindex',
            new_name='integration_bucket__7af454_idx',
            old_name='integratio_bucket__fe0305_idx',
        ),
        migrations.RenameIndex(
            model_name='integrationapikey',
            new_name='integration_active_d24c3e_idx',
            old_name='integratio_active_f8f624_idx',
        ),
        migrations.RenameIndex(
            model_name='integrationapikey',
            new_name='integration_client__e71632_idx',
            old_name='integratio_client__97a794_idx',
        ),
        migrations.RenameIndex(
            model_name='integrationclient',
            new_name='integration_active_2fc45a_idx',
            old_name='integratio_active_8183c6_idx',
        ),
        migrations.RenameIndex(
            model_name='integrationclient',
            new_name='integration_bucket__c04460_idx',
            old_name='integratio_bucket__a0e6ce_idx',
        ),
    ]
