# Generated by Django 5.2.4 on 2026-04-27 00:00

from django.db import migrations, models


def infer_document_family(value: str) -> str:
    normalized = (value or "").lower()

    if (
        "verbale" in normalized
        and (
            "cda" in normalized
            or "consiglio di amministrazione" in normalized
        )
    ):
        return "verbale_cda"

    if (
        "estratto" in normalized
        and (
            "cda" in normalized
            or "consiglio di amministrazione" in normalized
        )
    ):
        return "estratto_cda"

    if "bilancio" in normalized:
        return "bilancio"

    if (
        "relazione" in normalized
        and "struttura organizzativa" in normalized
    ):
        return "relazione_struttura_organizzativa"

    if any(
        pattern in normalized
        for pattern in [
            "internal audit",
            "audit",
            "compliance",
            "risk management",
            "relazione ia",
            "relazione rm",
            "relazione cpl",
            "antiriciclaggio",
            "aml",
        ]
    ):
        return "report_controlli"

    if (
        "policy" in normalized
        and any(
            pattern in normalized
            for pattern in [
                "invest",
                "portafogli",
                "delega",
            ]
        )
    ):
        return "policy_investimento"

    if any(pattern in normalized for pattern in ["materiali", "documenti"]):
        return "materiale_supporto"

    return "altro"


def backfill_document_family(apps, schema_editor):
    DocumentIndex = apps.get_model("integrations", "DocumentIndex")

    for document in DocumentIndex.objects.all().only("id", "object_key"):
        document.document_family = infer_document_family(document.object_key)
        document.save(update_fields=["document_family"])


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_rename_integratio_client__c0a241_idx_integration_client__4b6cfb_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentindex",
            name="document_family",
            field=models.CharField(default="altro", max_length=64),
        ),
        migrations.AddIndex(
            model_name="documentindex",
            index=models.Index(
                fields=["client", "active", "document_family"],
                name="integration_client__ca25f1_idx",
            ),
        ),
        migrations.RunPython(
            backfill_document_family,
            migrations.RunPython.noop,
        ),
    ]
