# Generated by Django 5.2.4 on 2026-04-27 00:00

from django.db import migrations, models


def infer_control_function_tags(value: str) -> str:
    normalized = (value or "").lower()
    tags = []

    tag_patterns = [
        ("risk", ["risk management", "risk", "rm"]),
        ("compliance", ["compliance", "cpl"]),
        ("internal_audit", ["internal audit", "audit", "ia"]),
        ("aml", ["aml", "antiriciclaggio"]),
    ]

    for tag, patterns in tag_patterns:
        if any(pattern in normalized for pattern in patterns):
            tags.append(tag)

    return ",".join(tags)


def backfill_control_function_tags(apps, schema_editor):
    DocumentIndex = apps.get_model("integrations", "DocumentIndex")

    for document in DocumentIndex.objects.all().only("id", "object_key"):
        document.control_function_tags = infer_control_function_tags(
            document.object_key
        )
        document.save(update_fields=["control_function_tags"])


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_documentindex_document_family"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentindex",
            name="control_function_tags",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddIndex(
            model_name="documentindex",
            index=models.Index(
                fields=["client", "active", "control_function_tags"],
                name="integration_client__15a64c_idx",
            ),
        ),
        migrations.RunPython(
            backfill_control_function_tags,
            migrations.RunPython.noop,
        ),
    ]
