# Generated by Django 5.2.4 on 2026-04-27 00:00

from django.db import migrations, models


def infer_topic_tags(value: str) -> str:
    normalized = (value or "").lower()
    tags = []

    tag_patterns = [
        ("consob", ["consob"]),
        ("contestazioni", ["contestazione", "contestazioni"]),
        ("nomina", ["nomina", "nominato", "nominare"]),
        ("poteri", ["poteri", "potere"]),
        ("deleghe", ["deleghe", "delega"]),
        ("bilancio", ["bilancio"]),
        (
            "market_abuse",
            ["market abuse", "operazioni sospette", "ordini sospetti"],
        ),
        ("struttura_organizzativa", ["struttura organizzativa"]),
        (
            "politica_investimento",
            ["politica di investimento", "politiche di investimento"],
        ),
        ("rimedi", ["rimedi", "remediation", "azioni correttive"]),
        ("rilievi", ["rilievi", "finding", "findings", "raccomandazioni"]),
    ]

    for tag, patterns in tag_patterns:
        if any(pattern in normalized for pattern in patterns):
            tags.append(tag)

    return ",".join(tags)


def backfill_topic_tags(apps, schema_editor):
    DocumentIndex = apps.get_model("integrations", "DocumentIndex")

    for document in DocumentIndex.objects.all().only("id", "object_key"):
        document.topic_tags = infer_topic_tags(document.object_key)
        document.save(update_fields=["topic_tags"])


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_documentindex_control_function_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentindex",
            name="topic_tags",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddIndex(
            model_name="documentindex",
            index=models.Index(
                fields=["client", "active", "topic_tags"],
                name="integration_client__e2c2e0_idx",
            ),
        ),
        migrations.RunPython(
            backfill_topic_tags,
            migrations.RunPython.noop,
        ),
    ]
