# Generated by Django 5.2.4 on 2026-05-13 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_documentindex_approval_date'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documentindex',
            new_name='integration_client__3144c7_idx',
            old_name='integration_client__ca25f1_idx',
        ),
        migrations.RenameIndex(
            model_name='documentindex',
            new_name='integration_client__a282ad_idx',
            old_name='integration_client__15a64c_idx',
        ),
        migrations.RenameIndex(
            model_name='documentindex',
            new_name='integration_client__818c6d_idx',
            old_name='integration_client__e2c2e0_idx',
        ),
        migrations.RenameIndex(
            model_name='documentindex',
            new_name='integration_client__122c67_idx',
            old_name='integratio_client__semdate_idx',
        ),
        migrations.RenameIndex(
            model_name='documentindex',
            new_name='integration_client__5ec002_idx',
            old_name='integratio_client__appdate_idx',
        ),
        migrations.RenameIndex(
            model_name='documentindex',
            new_name='integration_client__e21c94_idx',
            old_name='integratio_client__s3lmod_idx',
        ),
    ]
