"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os
from celery.schedules import crontab
from datetime import datetime

load_dotenv()

# File storage backend selector.
FILE_STORAGE_BACKEND = os.environ.get('FILE_STORAGE_BACKEND', 'filesystem').lower()

# Environment Keys
OPENAI_KEY = os.environ['OPENAI_KEY']
DEEPL_KEY = os.environ['DEEPL_KEY']

# OPENAI_ASSISTANT_ID_RBYC_LAW_CONSULTANT = os.environ.get('OPENAI_ASSISTANT_ID_RBYC_LAW_CONSULTANT')

OPENAI_PROMPT_ID_RICERCA_DOCUMENTALE= os.environ.get('OPENAI_PROMPT_ID_RICERCA_DOCUMENTALE')
OPENAI_PROMPT_ID_CHECK_COMPLIANCE_RBYC = os.environ.get('OPENAI_PROMPT_ID_CHECK_COMPLIANCE_RBYC')
OPENAI_PROMPT_ID_DRAFT_DOCUMENT = os.environ.get('OPENAI_PROMPT_ID_DRAFT_DOCUMENT')

S3_UPLOAD_API_KEY = os.environ.get('S3_UPLOAD_API_KEY')
S3_UPLOAD_JWT_SECRET = os.environ.get('S3_UPLOAD_JWT_SECRET')

AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME')

FUNCTIONALITY_DOCUMENTS_BUCKET_NAME = os.environ.get('FUNCTIONALITY_DOCUMENTS_BUCKET_NAME')

QUICKDOC_VERBALE_CDA_TEMPLATE_KEY = os.environ.get('QUICKDOC_VERBALE_CDA_TEMPLATE_KEY')
QUICKDOC_VERBALE_CDA_TEMPLATE_URL = os.environ.get('QUICKDOC_VERBALE_CDA_TEMPLATE_URL')

MAILAPI_API_KEY = os.environ.get('MAILAPI_API_KEY')
FRONTEND_URL = os.environ.get('FRONTEND_URL')

INTEGRATION_API_KEY = os.environ.get('INTEGRATION_API_KEY')

PERPLEXITY_API_KEY = os.environ.get('PERPLEXITY_API_KEY')

COST_AGGREGATOR_API_KEY = os.environ.get('COST_AGGREGATOR_API_KEY')
COST_AGGREGATOR_PROJECT_ID = os.environ.get('COST_AGGREGATOR_PROJECT_ID')
COST_AGGREGATOR_PROJECT_NAME = os.environ.get('COST_AGGREGATOR_PROJECT_NAME')
COST_AGGREGATOR_DEFAULT_CURRENCY = os.environ.get('COST_AGGREGATOR_DEFAULT_CURRENCY', 'EUR')

USAGE_DEFAULT_PRICES = {
    "RICERCA_DOCUMENTALE": "0.10",  # euros por consulta
    "DRAFT_DOCUMENT": "0.10",  # euros por página analisada
    "CHECK_COMPLIANCE": "0.45",  # euros por página analisada
    "CHAT_ASSISTANT": {
        "GPT-5.2": "0.10",
        "GEMINI_3_PRO_PREVIEW": "0.10",
        "PERPLEXITY": "0.20",
    },
    "SEGRETERIA_SOCIETARIA": {
        "DOCUMENTI_AI": "0.10",
        "ASSISTENTE_LEGALE": "0.10",
    },
}

MCP_SERVER_URL = os.environ.get('MCP_SERVER_URL', 'https://mcp-server-ricerca-rbyc.onrender.com/sse')


keys = [
    'OPENAI_KEY',
    'DEEPL_KEY',
    'OPENAI_PROMPT_ID_RICERCA_DOCUMENTALE',
    'OPENAI_PROMPT_ID_CHECK_COMPLIANCE_RBYC',
    'OPENAI_PROMPT_ID_DRAFT_DOCUMENT',
    'S3_UPLOAD_API_KEY',
    'S3_UPLOAD_JWT_SECRET',
    'AWS_ACCESS_KEY_ID',
    'AWS_SECRET_ACCESS_KEY',
    'AWS_S3_REGION_NAME',
    'AWS_STORAGE_BUCKET_NAME',
    'FUNCTIONALITY_DOCUMENTS_BUCKET_NAME',
    'MAILAPI_API_KEY',
    'FRONTEND_URL',
    'INTEGRATION_API_KEY',
    'PERPLEXITY_API_KEY',
    'COST_AGGREGATOR_API_KEY',
    'COST_AGGREGATOR_PROJECT_ID',
    'COST_AGGREGATOR_PROJECT_NAME',
    'MCP_SERVER_URL'
]

missing_keys = [key for key in keys if not os.getenv(key)]

if missing_keys:
    raise Exception(
        f"The following environment variables are not set: {', '.join(missing_keys)}")

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_TIMEZONE = "Europe/Rome"

now = datetime.now()
current_year = now.year

CELERY_BEAT_SCHEDULE = {
    'news_sector_morning': {
        'task': 'core.tasks.test_task',
        'schedule': crontab(hour=8, minute=0),
        'args': ('test',)
    },
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        '': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a!$duvz(gemholwmq(0q3y5&aeh@b$%g(2hgajbyh%^2i!jcbx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    'rbyc.admind.ai',
    'backoffice.admind.ai',
    '54.93.106.73', # Public ip of backoffice server
]
CORS_ALLOW_ALL_ORIGINS = True


# Application definition
DEFAULT_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "drf_spectacular"
]

THIRD_PARTY_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_extensions',
    'storages',
]

LOCAL_APPS = [
    'core.apps.CoreConfig',
    'users',
    'integrations'
]

INSTALLED_APPS = DEFAULT_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('Bearer',),
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'TOKEN_OBTAIN_SERIALIZER': 'users.serializers.CustomTokenObtainPairSerializer',
}

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = "users.CustomUser"


# Define the root directory for collected media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Define the root directory for collected static files
STATIC_URL = 'staticfiles/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Storage configuration for handling static and media files.
if FILE_STORAGE_BACKEND == 's3':
    default_storage_backend = "storages.backends.s3.S3Storage"
else:
    default_storage_backend = "django.core.files.storage.FileSystemStorage"

STORAGES = {
    "default": {
        "BACKEND": default_storage_backend,
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    }
}

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    "TITLE": "Integrations API",
    "VERSION": "1.0.0",

    "SERVERS": [
        {
            "url": "/api/integrations",
            "description": "Integrations API",
        }
    ],

    "SECURITY": [{"ApiKeyAuth": []}],

    "COMPONENTS": {
        "securitySchemes": {
            "ApiKeyAuth": {
                "type": "apiKey",
                "in": "header",
                "name": "Authorization",
                "description": "Use: Api-Key <sua_api_key>",
            }
        }
    },
}


# LOCAL
# STORAGES = {
#     "default": {
#         "BACKEND": "django.core.files.storage.FileSystemStorage",
#     },
#     "staticfiles": {
#         "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
#     }
# }
