"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os
from celery.schedules import crontab
from datetime import datetime

load_dotenv()

# File storage backend selector.
FILE_STORAGE_BACKEND = os.environ.get('FILE_STORAGE_BACKEND', 'filesystem').lower()

# Environment Keys
OPENAI_KEY = os.environ['OPENAI_KEY']
DEEPL_KEY = os.environ['DEEPL_KEY']

# OPENAI_ASSISTANT_ID_RBYC_LAW_CONSULTANT = os.environ.get('OPENAI_ASSISTANT_ID_RBYC_LAW_CONSULTANT')

OPENAI_PROMPT_ID_RICERCA_DOCUMENTALE= os.environ.get('OPENAI_PROMPT_ID_RICERCA_DOCUMENTALE')
OPENAI_PROMPT_ID_CHECK_COMPLIANCE_RBYC = os.environ.get('OPENAI_PROMPT_ID_CHECK_COMPLIANCE_RBYC')
OPENAI_PROMPT_ID_DRAFT_DOCUMENT = os.environ.get('OPENAI_PROMPT_ID_DRAFT_DOCUMENT')

S3_UPLOAD_API_KEY = os.environ.get('S3_UPLOAD_API_KEY')
S3_UPLOAD_JWT_SECRET = os.environ.get('S3_UPLOAD_JWT_SECRET')

AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME')
COMPLIANCE_DOCUMENTS_BUCKET_NAME = os.environ.get(
    'COMPLIANCE_DOCUMENTS_BUCKET_NAME',
    'rbyc-compliance-knowledge-prod',
)
COMPLIANCE_DOCUMENTS_BUCKET_REGION = os.environ.get(
    'COMPLIANCE_DOCUMENTS_BUCKET_REGION',
    'eu-central-1',
)
COMPLIANCE_CHAT_BUCKET_NAME = os.environ.get('COMPLIANCE_CHAT_BUCKET_NAME')
COMPLIANCE_CHAT_UPLOAD_PREFIX = os.environ.get(
    'COMPLIANCE_CHAT_UPLOAD_PREFIX',
    'documents/chat-uploads/',
)
COMPLIANCE_CHAT_MAX_UPLOAD_SIZE = int(
    os.environ.get('COMPLIANCE_CHAT_MAX_UPLOAD_SIZE', str(200 * 1024 * 1024))
)
VERA_API_BASE_URL = os.environ.get('VERA_API_BASE_URL', 'https://vera-api.admind.ai/v1')
VERA_API_SERVER_KEY = os.environ.get('VERA_API_SERVER_KEY')
VERA_API_MODEL = os.environ.get('VERA_API_MODEL', 'vera-compliance')
VERA_API_TIMEOUT_SECONDS = float(os.environ.get('VERA_API_TIMEOUT_SECONDS', '900'))
VERA_API_MAX_RETRIES = int(os.environ.get('VERA_API_MAX_RETRIES', '2'))
VERA_API_RETRY_BACKOFF_SECONDS = float(os.environ.get('VERA_API_RETRY_BACKOFF_SECONDS', '2'))
VERA_API_STREAM_KEEPALIVE_SECONDS = float(os.environ.get('VERA_API_STREAM_KEEPALIVE_SECONDS', '60'))
VERA_DEFAULT_ORGANIZATION_ID = os.environ.get('VERA_DEFAULT_ORGANIZATION_ID')
VERA_DEFAULT_CLIENT_ID = os.environ.get('VERA_DEFAULT_CLIENT_ID')
VERA_DEFAULT_MATTER_ID = os.environ.get('VERA_DEFAULT_MATTER_ID')

FUNCTIONALITY_DOCUMENTS_BUCKET_NAME = os.environ.get('FUNCTIONALITY_DOCUMENTS_BUCKET_NAME')

QUICKDOC_VERBALE_CDA_TEMPLATE_KEY = os.environ.get('QUICKDOC_VERBALE_CDA_TEMPLATE_KEY')
QUICKDOC_VERBALE_CDA_TEMPLATE_URL = os.environ.get('QUICKDOC_VERBALE_CDA_TEMPLATE_URL')

MAILAPI_API_KEY = os.environ.get('MAILAPI_API_KEY')
FRONTEND_URL = os.environ.get('FRONTEND_URL')

INTEGRATION_API_KEY = os.environ.get('INTEGRATION_API_KEY')

PERPLEXITY_API_KEY = os.environ.get('PERPLEXITY_API_KEY')

COST_AGGREGATOR_API_KEY = os.environ.get('COST_AGGREGATOR_API_KEY')
COST_AGGREGATOR_PROJECT_ID = os.environ.get('COST_AGGREGATOR_PROJECT_ID')
COST_AGGREGATOR_PROJECT_NAME = os.environ.get('COST_AGGREGATOR_PROJECT_NAME')
COST_AGGREGATOR_DEFAULT_CURRENCY = os.environ.get('COST_AGGREGATOR_DEFAULT_CURRENCY', 'EUR')
INTERNAL_COSTS_TOKEN = os.environ.get('INTERNAL_COSTS_TOKEN') or COST_AGGREGATOR_API_KEY
INTERNAL_COSTS_PROJECT_ID = os.environ.get('PROJECT_ID') or COST_AGGREGATOR_PROJECT_ID
INTERNAL_COSTS_PROJECT_NAME = os.environ.get('PROJECT_NAME') or COST_AGGREGATOR_PROJECT_NAME
INTERNAL_COSTS_DEFAULT_CURRENCY = os.environ.get('DEFAULT_CURRENCY') or COST_AGGREGATOR_DEFAULT_CURRENCY
INTERNAL_COSTS_AWS_REGION = os.environ.get('AWS_REGION') or AWS_S3_REGION_NAME
INTERNAL_COSTS_USD_TO_EUR_RATE = os.environ.get('INTERNAL_COSTS_USD_TO_EUR_RATE')
INTERNAL_COSTS_FX_DATE = os.environ.get('INTERNAL_COSTS_FX_DATE')
INTERNAL_COSTS_FX_TIMEOUT_SECONDS = os.environ.get('INTERNAL_COSTS_FX_TIMEOUT_SECONDS', '10')

STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET')
BILLING_DEFAULT_CURRENCY = os.environ.get('BILLING_DEFAULT_CURRENCY', 'EUR')
BILLING_STRIPE_IDEMPOTENCY_PREFIX = os.environ.get('BILLING_STRIPE_IDEMPOTENCY_PREFIX', 'rbyc')
BILLING_INVOICE_DESCRIPTION_PREFIX = os.environ.get(
    'BILLING_INVOICE_DESCRIPTION_PREFIX',
    'RbyC AI - Invoice for {period_month:%Y-%m}'
)
BILLING_COMPANY_MARKUP_PERCENTAGE = os.environ.get('BILLING_COMPANY_MARKUP_PERCENTAGE', '20')
BILLING_IVA_PERCENTAGE = os.environ.get('BILLING_IVA_PERCENTAGE', '22')
OPENAI_ADMIN_KEY = os.environ.get('OPENAI_ADMIN_KEY')
OPENAI_COSTS_PROJECT_ID = os.environ.get('OPENAI_COSTS_PROJECT_ID') or os.environ.get('OPENAI_PROJECT_ID')


MCP_SERVER_URL = os.environ.get('MCP_SERVER_URL', 'https://mcp-server-ricerca-rbyc.onrender.com/sse')
CHECK_COMPLIANCE_MCP_SERVER_URL = os.environ.get('CHECK_COMPLIANCE_MCP_SERVER_URL')
DOCUMENT_INDEX_API_KEY = os.environ.get('DOCUMENT_INDEX_API_KEY')
DOCUMENT_INDEX_API_URL = os.environ.get('DOCUMENT_INDEX_API_URL')
DOCUMENT_INDEX_CUSTOMER_CODE = os.environ.get('DOCUMENT_INDEX_CUSTOMER_CODE', 'default')


keys = [
    'OPENAI_KEY',
    'DEEPL_KEY',
    'OPENAI_PROMPT_ID_RICERCA_DOCUMENTALE',
    'OPENAI_PROMPT_ID_CHECK_COMPLIANCE_RBYC',
    'OPENAI_PROMPT_ID_DRAFT_DOCUMENT',
    'S3_UPLOAD_API_KEY',
    'S3_UPLOAD_JWT_SECRET',
    'AWS_ACCESS_KEY_ID',
    'AWS_SECRET_ACCESS_KEY',
    'AWS_S3_REGION_NAME',
    'AWS_STORAGE_BUCKET_NAME',
    'FUNCTIONALITY_DOCUMENTS_BUCKET_NAME',
    'MAILAPI_API_KEY',
    'FRONTEND_URL',
    'INTEGRATION_API_KEY',
    'PERPLEXITY_API_KEY',
    'MCP_SERVER_URL'
]

missing_keys = [key for key in keys if not os.getenv(key)]

if missing_keys:
    raise Exception(
        f"The following environment variables are not set: {', '.join(missing_keys)}")

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_TIMEZONE = "Europe/Rome"
DOCUMENT_INDEX_SYNC_MINUTES = int(os.environ.get('DOCUMENT_INDEX_SYNC_MINUTES', '15'))
DOCUMENT_PREVIEW_SYNC_MINUTES = int(os.environ.get('DOCUMENT_PREVIEW_SYNC_MINUTES', '10'))
DOCUMENT_PREVIEW_SYNC_LIMIT = int(os.environ.get('DOCUMENT_PREVIEW_SYNC_LIMIT', '100'))
DOCUMENT_PREVIEW_SYNC_CUSTOMER_CODE = os.environ.get(
    'DOCUMENT_PREVIEW_SYNC_CUSTOMER_CODE',
    '',
).strip()
DOCUMENT_PREVIEW_SYNC_PROCESS_ALL = os.environ.get(
    'DOCUMENT_PREVIEW_SYNC_PROCESS_ALL',
    'false',
).strip().lower() in {'1', 'true', 'yes', 'on'}
DOCUMENT_PREVIEW_SYNC_MAX_BATCHES = int(
    os.environ.get('DOCUMENT_PREVIEW_SYNC_MAX_BATCHES', '0')
)

now = datetime.now()
current_year = now.year

CELERY_BEAT_SCHEDULE = {
    'news_sector_morning': {
        'task': 'core.tasks.test_task',
        'schedule': crontab(hour=8, minute=0),
        'args': ('test',)
    },
    'sync_document_indexes': {
        'task': 'integrations.tasks.sync_all_document_indexes_task',
        'schedule': crontab(minute=f'*/{DOCUMENT_INDEX_SYNC_MINUTES}'),
        'kwargs': {'deactivate_missing': False},
    },
    'build_document_previews': {
        'task': 'integrations.tasks.build_missing_document_previews_task',
        'schedule': crontab(minute=f'*/{DOCUMENT_PREVIEW_SYNC_MINUTES}'),
        'kwargs': {
            'customer_code': DOCUMENT_PREVIEW_SYNC_CUSTOMER_CODE,
            'limit': DOCUMENT_PREVIEW_SYNC_LIMIT,
            'force': False,
            'process_all': DOCUMENT_PREVIEW_SYNC_PROCESS_ALL,
            'max_batches': DOCUMENT_PREVIEW_SYNC_MAX_BATCHES,
        },
    },
    'generate_monthly_billing_invoice': {
        'task': 'billing.tasks.generate_monthly_billing_invoice',
        'schedule': crontab(day_of_month=1, hour=6, minute=0),
    },
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        '': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a!$duvz(gemholwmq(0q3y5&aeh@b$%g(2hgajbyh%^2i!jcbx'

MCP_INTERNAL_AUTH_SECRET = (
    os.environ.get('MCP_INTERNAL_AUTH_SECRET')
    or INTEGRATION_API_KEY
    or SECRET_KEY
)
MCP_INTERNAL_AUTH_ISSUER = os.environ.get(
    'MCP_INTERNAL_AUTH_ISSUER',
    'backend-integrations',
)
MCP_INTERNAL_AUTH_AUDIENCE = os.environ.get(
    'MCP_INTERNAL_AUTH_AUDIENCE',
    'mcp-ricerca',
)
MCP_INTERNAL_AUTH_TTL_SECONDS = int(
    os.environ.get('MCP_INTERNAL_AUTH_TTL_SECONDS', '300')
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    'rbyc.admind.ai',
    'backoffice.admind.ai',
    '54.93.106.73', # Public ip of backoffice server
]
CORS_ALLOW_ALL_ORIGINS = True


# Application definition
DEFAULT_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "drf_spectacular"
]

THIRD_PARTY_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_extensions',
    'storages',
]

LOCAL_APPS = [
    'core.apps.CoreConfig',
    'billing.apps.BillingConfig',
    'users',
    'integrations'
]

INSTALLED_APPS = DEFAULT_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('Bearer',),
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'TOKEN_OBTAIN_SERIALIZER': 'users.serializers.CustomTokenObtainPairSerializer',
}

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if os.environ.get("DB_ENGINE") == "django.db.backends.postgresql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME"),
            "USER": os.environ.get("DB_USER"),
            "PASSWORD": os.environ.get("DB_PASSWORD"),
            "HOST": os.environ.get("DB_HOST", "127.0.0.1"),
            "PORT": os.environ.get("DB_PORT", "5432"),
            "CONN_MAX_AGE": int(os.environ.get("DB_CONN_MAX_AGE", "60")),
            "CONN_HEALTH_CHECKS": True,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = "users.CustomUser"


# Define the root directory for collected media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Define the root directory for collected static files
STATIC_URL = 'staticfiles/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Storage configuration for handling static and media files.
if FILE_STORAGE_BACKEND == 's3':
    default_storage_backend = "storages.backends.s3.S3Storage"
else:
    default_storage_backend = "django.core.files.storage.FileSystemStorage"

STORAGES = {
    "default": {
        "BACKEND": default_storage_backend,
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    }
}

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    "TITLE": "Integrations API",
    "VERSION": "1.0.0",

    "SERVERS": [
        {
            "url": "/api/integrations",
            "description": "Integrations API",
        }
    ],

    "SECURITY": [{"ApiKeyAuth": []}],

    "COMPONENTS": {
        "securitySchemes": {
            "ApiKeyAuth": {
                "type": "apiKey",
                "in": "header",
                "name": "Authorization",
                "description": "Use: Api-Key <sua_api_key>",
            }
        }
    },
}


# LOCAL
# STORAGES = {
#     "default": {
#         "BACKEND": "django.core.files.storage.FileSystemStorage",
#     },
#     "staticfiles": {
#         "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
#     }
# }
