// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/layout-refresh/Airy.tsx": () => import("../components/mockups/layout-refresh/Airy.tsx"),
  "./components/mockups/layout-refresh/Polished.tsx": () => import("../components/mockups/layout-refresh/Polished.tsx")
};
