# Generated by Django 5.0.3 on 2025-06-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('doc_format', models.CharField(max_length=64)),
                ('language', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('word_file', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
    ]
