# Generated by Django 5.0.3 on 2025-07-28 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='chatconversation',
            options={'verbose_name': 'Chat - Conversation', 'verbose_name_plural': 'Chat - Conversations'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'verbose_name': 'Chat - Message', 'verbose_name_plural': 'Chat - Messages'},
        ),
        migrations.RemoveConstraint(
            model_name='chatconversation',
            name='unique_conversation_name',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='citations',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='file',
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='name',
            field=models.CharField(default='New Chat', max_length=100),
        ),
        migrations.AddField(
            model_name='assistantthread',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='core.chatconversation'),
        ),
    ]
