# Generated by Django 5.2.3 on 2025-09-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_assistantthread_alter_chatconversation_options_and_more'),
        ('users', '0002_remove_customuser_company_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistantthread',
            options={'verbose_name': 'Chat - Thread', 'verbose_name_plural': 'Chat - Threads'},
        ),
        migrations.DeleteModel(
            name='CEO',
        ),
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
    ]
