# Generated by Django 5.2.3 on 2025-09-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_assistantthread_options_delete_ceo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatconversation',
            name='is_new',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='citations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat/'),
        ),
    ]
