# Generated by Django 5.2.3 on 2025-09-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_chatconversation_is_new_chatmessage_citations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
