# Generated by Django 5.2.3 on 2025-09-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chatconversation_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='is_chat_rag',
            field=models.BooleanField(default=False),
        ),
    ]
