# Generated by Django 5.2.3 on 2025-09-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_chatconversation_is_chat_rag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'Chat - Message', 'verbose_name_plural': 'Chat - Messages'},
        ),
    ]
