# Generated by Django 5.2.4 on 2025-11-25 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_chatmessage_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Ragione Sociale"),
                ),
                (
                    "vat_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Partita IVA"
                    ),
                ),
                (
                    "company_type",
                    models.CharField(
                        choices=[
                            ("S.r.l.", "S.r.l."),
                            ("S.p.A.", "S.p.A."),
                            ("S.a.p.a.", "S.a.p.a."),
                            ("S.r.l.s.", "S.r.l.s."),
                        ],
                        default="S.r.l.",
                        max_length=20,
                        verbose_name="Tipo Società",
                    ),
                ),
                ("address", models.TextField(verbose_name="Sede Legale")),
                (
                    "capital",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Capitale Sociale"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Attiva"),
                            ("Liquidation", "In Liquidazione"),
                            ("Inactive", "Inattiva"),
                        ],
                        default="Active",
                        max_length=20,
                        verbose_name="Stato",
                    ),
                ),
                (
                    "next_meeting_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Prossima Assemblea"
                    ),
                ),
                (
                    "letterhead_info",
                    models.TextField(
                        blank=True, null=True, verbose_name="Testo Intestazione"
                    ),
                ),
                (
                    "letterhead_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="letterheads/",
                        verbose_name="File Intestazione",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Società",
                "verbose_name_plural": "Società",
            },
        ),
        migrations.CreateModel(
            name="Deadline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titolo")),
                ("due_date", models.DateField(verbose_name="Data Scadenza")),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Completata"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TAX", "Fiscale"),
                            ("CORPORATE", "Societario"),
                            ("LEGAL", "Legale"),
                        ],
                        default="CORPORATE",
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deadlines",
                        to="core.company",
                        verbose_name="Società",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scadenza",
                "verbose_name_plural": "Scadenze",
                "ordering": ["due_date"],
            },
        ),
    ]
