# Generated by Django 5.2.4 on 2025-11-25 06:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_company_deadline"),
    ]

    operations = [
        migrations.CreateModel(
            name="Officer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nome e Cognome"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Amministratore Unico", "Amministratore Unico"),
                            ("Consigliere", "Consigliere"),
                            ("Presidente CdA", "Presidente CdA"),
                            ("Sindaco", "Sindaco"),
                            ("Revisore", "Revisore"),
                        ],
                        max_length=50,
                        verbose_name="Carica",
                    ),
                ),
                ("appointed_date", models.DateField(verbose_name="Data Nomina")),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Scadenza"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="officers",
                        to="core.company",
                        verbose_name="Società",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carica Sociale",
                "verbose_name_plural": "Cariche Sociali",
            },
        ),
        migrations.CreateModel(
            name="Shareholder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome Socio")),
                (
                    "quota_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Quota %",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shareholders",
                        to="core.company",
                        verbose_name="Società",
                    ),
                ),
            ],
            options={
                "verbose_name": "Socio",
                "verbose_name_plural": "Soci",
            },
        ),
    ]
