# Generated by Django 5.2.4 on 2025-12-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_make_company_fields_optional"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyDocumentLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("letterhead_base64", models.TextField(blank=True, null=True)),
                ("word_letterhead_base64", models.TextField(blank=True, null=True)),
                (
                    "document_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
