# Generated by Django 5.2.4 on 2026-02-03 00:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_companydocumentlayout"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerplexityConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conversation_id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("memory_summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="PerplexityMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("system", "system"),
                            ("user", "user"),
                            ("assistant", "assistant"),
                        ],
                        max_length=16,
                    ),
                ),
                ("content", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("included_in_summary", models.BooleanField(default=False)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.perplexityconversation",
                    ),
                ),
            ],
            options={"ordering": ["created_at"]},
        ),
    ]
