# Generated by Django 5.2.4 on 2026-02-04 02:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_perplexity_conversation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoredChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("gpt", "GPT / OpenAI"),
                            ("perplexity", "Perplexity"),
                            ("gemini", "Gemini"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "external_conversation_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("display_model", models.CharField(blank=True, max_length=64)),
                ("title", models.CharField(default="New Chat", max_length=255)),
                ("is_saved", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stored_chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="StoredChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("system", "system"),
                            ("user", "user"),
                            ("assistant", "assistant"),
                        ],
                        max_length=16,
                    ),
                ),
                ("content", models.JSONField(default=list)),
                ("provider_payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.storedchatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="storedchatsession",
            index=models.Index(
                fields=["provider", "user", "is_saved"],
                name="core_stored_provide_6c68e1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="storedchatsession",
            index=models.Index(
                fields=["external_conversation_id"],
                name="core_stored_externa_59c2d3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="storedchatsession",
            constraint=models.UniqueConstraint(
                fields=("user", "provider", "external_conversation_id"),
                name="unique_provider_external_conversation",
            ),
        ),
    ]
