# Generated by Django 5.2.4 on 2026-02-05 12:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_storedchatsession_storedchatmessage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tool",
                    models.CharField(
                        choices=[
                            ("RICERCA_DOCUMENTALE", "Ricerca documentale"),
                            ("DRAFT_DOCUMENT", "Draft document"),
                            ("CHECK_COMPLIANCE", "Check compliance"),
                            ("CHAT_ASSISTANT", "Chat assistant"),
                            ("SEGRETERIA_SOCIETARIA", "Segreteria societaria"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "sub_tool",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DOCUMENTI_AI", "Documenti AI"),
                            ("ASSISTENTE_LEGALE", "Assistente legale"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "unit_price_eur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tariffa di utilizzo",
                "verbose_name_plural": "Tariffe di utilizzo",
                "ordering": ["tool", "sub_tool", "-effective_from"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tool", "sub_tool", "effective_from"),
                        name="uniq_usage_rate_by_period",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tool",
                    models.CharField(
                        choices=[
                            ("RICERCA_DOCUMENTALE", "Ricerca documentale"),
                            ("DRAFT_DOCUMENT", "Draft document"),
                            ("CHECK_COMPLIANCE", "Check compliance"),
                            ("CHAT_ASSISTANT", "Chat assistant"),
                            ("SEGRETERIA_SOCIETARIA", "Segreteria societaria"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "sub_tool",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DOCUMENTI_AI", "Documenti AI"),
                            ("ASSISTENTE_LEGALE", "Assistente legale"),
                        ],
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                (
                    "unit_price_eur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "total_cost_eur",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_records",
                        to="core.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usage_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento di utilizzo",
                "verbose_name_plural": "Eventi di utilizzo",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["tool", "occurred_at"], name="usage_tool_date_idx"
                    ),
                    models.Index(
                        fields=["user", "occurred_at"], name="usage_user_date_idx"
                    ),
                ],
            },
        ),
    ]
