# Generated by Django 5.2.4 on 2026-02-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_usagerate_usagerecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usagerate",
            name="sub_tool",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GPT-5.2", "GPT-5.2"),
                    ("GEMINI_3_PRO_PREVIEW", "Gemini 3 Pro Preview"),
                    ("PERPLEXITY", "Perplexity"),
                    ("DOCUMENTI_AI", "Documenti AI"),
                    ("ASSISTENTE_LEGALE", "Assistente legale"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="usagerecord",
            name="sub_tool",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GPT-5.2", "GPT-5.2"),
                    ("GEMINI_3_PRO_PREVIEW", "Gemini 3 Pro Preview"),
                    ("PERPLEXITY", "Perplexity"),
                    ("DOCUMENTI_AI", "Documenti AI"),
                    ("ASSISTENTE_LEGALE", "Assistente legale"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
