# Generated by Django 5.2.4 on 2026-04-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_usagerate_sub_tool_alter_usagerecord_sub_tool'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedDocument',
        ),
    ]
