# Generated by Django 6.0.7 on 2026-07-17 17:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_checkcomplianceconversation_checkcompliancemessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(default='aggiornamento_normativa', max_length=100)),
                ('normativa', models.TextField()),
                ('autorita', models.CharField(blank=True, default='', max_length=255)),
                ('data_rilevazione', models.DateTimeField(blank=True, null=True)),
                ('versione_precedente', models.JSONField(blank=True, default=dict)),
                ('versione_nuova', models.JSONField(blank=True, default=dict)),
                ('riassunto_modifica', models.TextField(blank=True, default='')),
                ('tag', models.CharField(default='LOG', max_length=50)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_rilevazione', '-created_at'],
                'indexes': [models.Index(fields=['tag'], name='core_compli_tag_61f270_idx'), models.Index(fields=['autorita'], name='core_compli_autorit_873a1e_idx'), models.Index(fields=['data_rilevazione'], name='core_compli_data_ri_ad2700_idx')],
            },
        ),
    ]
