# Generated by Django 6.0.7 on 2026-07-17 17:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_compliance_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeraUsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, help_text='Data UTC del consumo')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic')], db_index=True, max_length=32)),
                ('model', models.CharField(blank=True, default='', help_text='Nome modello (es. gpt-4o, claude-3-5-sonnet)', max_length=128)),
                ('input_tokens', models.BigIntegerField(default=0)),
                ('output_tokens', models.BigIntegerField(default=0)),
                ('total_tokens', models.BigIntegerField(default=0)),
                ('request_count', models.IntegerField(default=1)),
                ('cost_eur', models.DecimalField(blank=True, decimal_places=6, help_text='Costo stimato in EUR, calcolato lato backend', max_digits=12, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Payload grezzo ricevuto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consumo Vera',
                'verbose_name_plural': 'Consumi Vera',
                'ordering': ['-date', 'provider'],
                'indexes': [models.Index(fields=['date', 'provider'], name='core_veraus_date_9b97fe_idx'), models.Index(fields=['provider', 'date'], name='core_veraus_provide_988eba_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'provider', 'model'), name='vera_usage_unique_day_provider_model')],
            },
        ),
    ]
