# Generated by Django 5.2.16 on 2026-07-21 15:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_vera_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagerecord',
            name='sub_tool',
            field=models.CharField(blank=True, choices=[('GPT-5.2', 'GPT-5.2'), ('GPT-5.6 Terra', 'GPT-5.6 Terra'), ('PERPLEXITY', 'Perplexity'), ('DOCUMENTI_AI', 'Documenti AI'), ('ASSISTENTE_LEGALE', 'Assistente legale')], max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('compliance_log', 'Log Compliance'), ('newsletter_auto', 'Newsletter Automatica'), ('consumption_report', 'Report Mensile Consumo'), ('consumption_low_balance', 'Saldo Wallet Basso'), ('consumption_threshold', 'Limite Mensile Raggiunto')], max_length=40)),
                ('title', models.CharField(max_length=512)),
                ('body', models.TextField(blank=True, default='')),
                ('reference_id', models.CharField(blank=True, default='', max_length=64)),
                ('reference_type', models.CharField(blank=True, default='', max_length=40)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read'], name='core_notifi_is_read_127eae_idx'), models.Index(fields=['notification_type'], name='core_notifi_notific_cbfe88_idx'), models.Index(fields=['created_at'], name='core_notifi_created_d0c445_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedNewsletter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('content', models.TextField()),
                ('newsletter_type', models.CharField(choices=[('newsletter', 'Newsletter'), ('pill', 'PILL Formativo')], default='newsletter', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manuale'), ('auto', 'Automatica')], default='manual', max_length=10)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source'], name='core_savedn_source_4b9576_idx'), models.Index(fields=['newsletter_type'], name='core_savedn_newslet_7d5dd6_idx'), models.Index(fields=['created_at'], name='core_savedn_created_cc43ca_idx')],
            },
        ),
    ]
